# FLCM Core Configuration
# Version: 1.0.0

# Slash command prefix for Claude Code
slashPrefix: FLCM

system:
  name: "FLCM - Friction Lab Content Maker"
  version: "1.0.0"
  mode: "development" # development | production
  
agents:
  collector:
    enabled: true
    timeout: 300 # seconds
    methodologies:
      - rice-framework
      - signal-extraction
  
  scholar:
    enabled: true
    timeout: 300
    methodologies:
      - progressive-depth
      - analogy-mapping
  
  creator:
    enabled: true
    timeout: 300
    methodologies:
      - spark-method
      - voice-dna
  
  adapter:
    enabled: true
    timeout: 300
    platforms:
      - linkedin
      - twitter
      - medium
      - substack

workflows:
  quick_mode:
    enabled: true
    max_duration: 1800 # 30 minutes
    agents:
      - collector
      - creator
    skip_learning: true
    
  standard_mode:
    enabled: true
    max_duration: 3600 # 60 minutes
    agents:
      - collector
      - scholar
      - creator
      - adapter
    full_pipeline: true

document_pipeline:
  format: "markdown"
  frontmatter: true
  obsidian_compatible: true
  auto_save: true
  
methodologies:
  transparency: true
  logging: true
  user_visibility: "full" # full | summary | minimal

user_preferences:
  default_mode: "quick"
  voice_profile: "default"
  platforms:
    primary: "linkedin"
    secondary: ["twitter", "medium"]
  
  obsidian:
    enabled: false
    vault_path: ""
    auto_file: false
    
validation:
  auto_validate: true
  strict_mode: false
  quality_threshold: 0.7

paths:
  templates: ".flcm-core/templates"
  methodologies: ".flcm-core/methodologies"
  tasks: ".flcm-core/tasks"
  output: "output"
  logs: "logs"

debug:
  enabled: true
  verbose: false
  log_level: "info" # debug | info | warning | error

# FLCM 2.0 Version Routing Configuration
flcm:
  defaultVersion: "1.0"  # Default to stable version
  userOverrides:
    enabled: true
    configPath: ".flcm/user-config.yaml"
  featureFlags:
    v2_mentor: false
    v2_creator: false
    v2_publisher: false
    v2_obsidian: false
    v2_beta_users: false
    v2_internal_testing: false

# Version-specific configurations
versions:
  "1.0":
    agents:
      - collector
      - scholar
      - creator
      - adapter
    pipeline:
      maxDepth: 5
      timeout: 20000
  "2.0":
    layers:
      - mentor
      - creator
      - publisher
    frameworks:
      enabled: true
      preload: false
    obsidian:
      enabled: false
      syncInterval: 5000

# Health check configuration
health:
  enabled: true
  interval: 60000  # 1 minute
  endpoints:
    v1: "/health/v1"
    v2: "/health/v2"
    combined: "/health"

# Migration settings
migration:
  enabled: true
  batchSize: 100
  validateData: true
  backupBeforeMigration: true